Fix game spec
addod19/RSpec-TicTacToe pull request #1
Opened 2019-09-28 10:29 UTC by addod19

2019-09-28 10:37 UTC, addod19 commented
resolved merge conflict

2019-09-28 19:48 UTC, Oghenebrume50 requested changes
Hi Team good start to this test, I was able to run it with a little tweak :smile: , please see the below comments for required changes 

-There should be positive and negative test cases for all test, that is if you test for a truthy outcome, you should test for a falsy outcome too.
Stickler is not working on this repo yet, please add it.

make changes and request for  a re-review :+1:

2019-09-28 19:48 UTC, Oghenebrume50 commented on spec/game_spec.rb
> +  tie = Board.new({
use let to declare these shared variables, the test wouldn't run like this

2019-09-28 19:48 UTC, Oghenebrume50 commented on spec/board_spec.rb
> +      "
This isn't really necessary though, you could check for the datatype our specific content, but creating a replica of something just to test if the replica is the same with the original, isn't much of a test

2019-10-01 01:03 UTC, Ispirett commented
**Hey, guys, you need to use the correct git-flow please make a pull request that merges to the development branch.
resubmit  or a review**

2019-10-24 11:49 UTC, closed without merging

2019-10-24 11:49 UTC, addod19 commented
closed